export type QuizQuestion = {
  id: string;
  level: number;
  levelName: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  source: string;
};

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // LEVEL 1
  {
    id: "l1_q1",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "How many Surahs are in the Holy Quran?",
    options: ["100", "114", "120", "110"],
    correctIndex: 1,
    explanation: "The Holy Quran consists of exactly 114 Surahs, starting with Al-Fatihah and ending with An-Nas.",
    source: "Authentic Quranic Compilation",
  },
  {
    id: "l1_q2",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "What is the first revelation sent down to Prophet Muhammad ﷺ?",
    options: ["Surah Al-Fatihah", "Surah Al-Ikhlas", "Surah Al-'Alaq (Iqra)", "Surah Yasin"],
    correctIndex: 2,
    explanation: "The first verses revealed to Prophet Muhammad ﷺ in Cave Hira were the first five verses of Surah Al-'Alaq.",
    source: "Sahih Bukhari, Hadith 3",
  },
  {
    id: "l1_q3",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "How many obligatory daily prayers (Salah) are prescribed for Muslims?",
    options: ["3", "4", "5", "7"],
    correctIndex: 2,
    explanation: "Muslims are obligated to perform 5 daily prayers: Fajr, Dhuhr, Asr, Maghrib, and Isha.",
    source: "Sahih Bukhari, Hadith 8",
  },
  {
    id: "l1_q4",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "In which city was Prophet Muhammad ﷺ born?",
    options: ["Madinah", "Makkah", "Jerusalem", "Taif"],
    correctIndex: 1,
    explanation: "Prophet Muhammad ﷺ was born in the blessed city of Makkah in the Year of the Elephant (570 CE).",
    source: "Ar-Raheeq Al-Makhtum",
  },
  {
    id: "l1_q5",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "Which Pillar of Islam comes immediately after the Shahada?",
    options: ["Fasting (Sawm)", "Prayer (Salah)", "Zakat", "Hajj"],
    correctIndex: 1,
    explanation: "Performing the 5 daily prayers (Salah) is the second pillar of Islam.",
    source: "Sahih Bukhari, Hadith 8",
  },
  {
    id: "l1_q6",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "What is the holy book revealed to Prophet Isa (Jesus) peace be upon him?",
    options: ["Tawrat", "Zabur", "Injeel", "Quran"],
    correctIndex: 2,
    explanation: "Allah revealed the Injeel (Gospel) to Prophet Isa (peace be upon him).",
    source: "Holy Quran, Surah Al-Ma'idah 5:46",
  },
  {
    id: "l1_q7",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "Which Islamic month is dedicated to obligatory fasting?",
    options: ["Rajab", "Sha'ban", "Ramadan", "Muharram"],
    correctIndex: 2,
    explanation: "Ramadan is the ninth month of the Islamic calendar in which Muslims observe fasting.",
    source: "Holy Quran, Surah Al-Baqarah 2:185",
  },
  {
    id: "l1_q8",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "What direction do Muslims face during prayer?",
    options: ["Qibla (Kaaba in Makkah)", "North", "East", "Jerusalem"],
    correctIndex: 0,
    explanation: "Muslims face the Qibla, which is the Sacred Kaaba in Makkah, Saudi Arabia.",
    source: "Holy Quran, Surah Al-Baqarah 2:144",
  },
  {
    id: "l1_q9",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "What is the opening Surah of the Quran?",
    options: ["Surah Al-Baqarah", "Surah Al-Fatihah", "Surah Al-Ikhlas", "Surah Al-Nas"],
    correctIndex: 1,
    explanation: "Surah Al-Fatihah ('The Opening') is the first chapter of the Holy Quran.",
    source: "Holy Quran, Surah 1",
  },
  {
    id: "l1_q10",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "Which companion was the first Caliph of Islam?",
    options: ["Umar ibn al-Khattab", "Abu Bakr as-Siddiq", "Uthman ibn Affan", "Ali ibn Abi Talib"],
    correctIndex: 1,
    explanation: "Abu Bakr as-Siddiq (may Allah be pleased with him) was elected as the first Rashidun Caliph.",
    source: "Sahih Bukhari, Hadith 3661",
  },

  // LEVEL 2
  {
    id: "l2_q1",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "What is the longest Surah in the Holy Quran?",
    options: ["Surah Ali 'Imran", "Surah An-Nisa", "Surah Al-Baqarah", "Surah Al-Ma'idah"],
    correctIndex: 2,
    explanation: "Surah Al-Baqarah is the longest Surah containing 286 verses.",
    source: "Holy Quran, Surah 2",
  },
  {
    id: "l2_q2",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which verse in the Quran is considered the greatest verse?",
    options: ["Ayat al-Kursi (2:255)", "Aamanar-Rasul (2:285)", "Surah Al-Ikhlas 1", "Surah Al-Fatihah 1"],
    correctIndex: 0,
    explanation: "Prophet Muhammad ﷺ declared Ayat al-Kursi (Surah Al-Baqarah 2:255) to be the greatest verse in the Quran.",
    source: "Sahih Muslim, Hadith 810",
  },
  {
    id: "l2_q3",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which Surah does not begin with Bismillah?",
    options: ["Surah At-Tawbah", "Surah Al-Anfal", "Surah Yunus", "Surah Hud"],
    correctIndex: 0,
    explanation: "Surah At-Tawbah (Surah 9) is the only chapter in the Quran that does not begin with Bismillah.",
    source: "Holy Quran, Surah At-Tawbah",
  },
  {
    id: "l2_q4",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "In which Surah is Bismillah mentioned twice?",
    options: ["Surah An-Naml", "Surah Al-Kahf", "Surah Ya-Sin", "Surah Ar-Rahman"],
    correctIndex: 0,
    explanation: "Surah An-Naml mentions Bismillah at the beginning and also in verse 30 inside Solomon's letter.",
    source: "Holy Quran, Surah An-Naml 27:30",
  },
  {
    id: "l2_q5",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which Prophet's story is described as 'the best of stories' in the Quran?",
    options: ["Prophet Musa", "Prophet Ibrahim", "Prophet Yusuf", "Prophet Isa"],
    correctIndex: 2,
    explanation: "Surah Yusuf is explicitly described by Allah as 'Ahsan al-Qasas' (the best of stories).",
    source: "Holy Quran, Surah Yusuf 12:3",
  },
  {
    id: "l2_q6",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which Surah is equivalent to one-third of the Quran in reward?",
    options: ["Surah Al-Fatihah", "Surah Al-Ikhlas", "Surah Al-Falaq", "Surah An-Nas"],
    correctIndex: 1,
    explanation: "Reciting Surah Al-Ikhlas is equivalent in reward to reciting one-third of the Quran.",
    source: "Sahih Bukhari, Hadith 5013",
  },
  {
    id: "l2_q7",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "How many Juz are in the Holy Quran?",
    options: ["20", "30", "40", "60"],
    correctIndex: 1,
    explanation: "The Quran is divided into 30 Juz (parts) for recitation structure.",
    source: "Authentic Quranic Structure",
  },
  {
    id: "l2_q8",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which female figure is the only woman mentioned by name in the Quran?",
    options: ["Khadijah", "Aisha", "Maryam (Mary)", "Asiya"],
    correctIndex: 2,
    explanation: "Maryam, the mother of Prophet Isa (peace be upon him), is the only woman explicitly named in the Quran.",
    source: "Holy Quran, Surah Maryam 19",
  },
  {
    id: "l2_q9",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which Surah protects its reciter from the punishment of the grave?",
    options: ["Surah Al-Mulk", "Surah Al-Kahf", "Surah Ya-Sin", "Surah Al-Waqi'ah"],
    correctIndex: 0,
    explanation: "Prophet Muhammad ﷺ said that Surah Al-Mulk (30 verses) intercedes for its reader until forgiven.",
    source: "Sunan an-Nasa'i, Hadith 10479",
  },
  {
    id: "l2_q10",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which Surah recommended to be read every Friday protects from Dajjal?",
    options: ["Surah Al-Kahf", "Surah Al-Baqarah", "Surah Yasin", "Surah Ar-Rahman"],
    correctIndex: 0,
    explanation: "Memorizing the first ten verses of Surah Al-Kahf protects against the trial of Dajjal.",
    source: "Sahih Muslim, Hadith 809",
  },

  // LEVEL 3
  {
    id: "l3_q1",
    level: 3,
    levelName: "Level 3 — Prophets & Messengers",
    question: "Which Prophet is known as Khalilullah (The Friend of Allah)?",
    options: ["Prophet Musa", "Prophet Ibrahim", "Prophet Isa", "Prophet Nuh"],
    correctIndex: 1,
    explanation: "Prophet Ibrahim (peace be upon him) was chosen by Allah as His Khalil (intimate friend).",
    source: "Holy Quran, Surah An-Nisa 4:125",
  },
  {
    id: "l3_q2",
    level: 3,
    levelName: "Level 3 — Prophets & Messengers",
    question: "Which Prophet spoke to Allah directly and is called Kaleemullah?",
    options: ["Prophet Musa", "Prophet Isa", "Prophet Dawud", "Prophet Yunus"],
    correctIndex: 0,
    explanation: "Prophet Musa (peace be upon him) spoke directly with Allah at Mount Sinai.",
    source: "Holy Quran, Surah An-Nisa 4:164",
  },
  {
    id: "l3_q3",
    level: 3,
    levelName: "Level 3 — Prophets & Messengers",
    question: "Which Prophet built the Ark by Allah's command?",
    options: ["Prophet Nuh", "Prophet Hud", "Prophet Salih", "Prophet Lut"],
    correctIndex: 0,
    explanation: "Prophet Nuh (Noah) built the Ark under divine direction to save believers from the Great Flood.",
    source: "Holy Quran, Surah Hud 11:37",
  },
  {
    id: "l3_q4",
    level: 3,
    levelName: "Level 3 — Prophets & Messengers",
    question: "Which Prophet was given the miracle of understanding the language of birds and animals?",
    options: ["Prophet Dawud", "Prophet Sulaiman", "Prophet Yusuf", "Prophet Ayub"],
    correctIndex: 1,
    explanation: "Prophet Sulaiman (Solomon) was taught the speech of birds and creatures.",
    source: "Holy Quran, Surah An-Naml 27:16",
  },
  {
    id: "l3_q5",
    level: 3,
    levelName: "Level 3 — Prophets & Messengers",
    question: "Which Prophet exhibited legendary patience during severe illness and loss?",
    options: ["Prophet Ayub", "Prophet Yunus", "Prophet Yahya", "Prophet Zakariya"],
    correctIndex: 0,
    explanation: "Prophet Ayub (Job) is celebrated in the Quran for his extraordinary patience and steadfast faith.",
    source: "Holy Quran, Surah Sad 38:44",
  },
  {
    id: "l3_q6",
    level: 3,
    levelName: "Level 3 — Prophets & Messengers",
    question: "Which Prophet remained inside the belly of a giant whale and supplicated to Allah?",
    options: ["Prophet Yunus", "Prophet Ilyas", "Prophet Al-Yasa", "Prophet Shu'ayb"],
    correctIndex: 0,
    explanation: "Prophet Yunus (Jonah) called upon Allah from the depths of the ocean inside the whale.",
    source: "Holy Quran, Surah Al-Anbiya 21:87",
  },
  {
    id: "l3_q7",
    level: 3,
    levelName: "Level 3 — Prophets & Messengers",
    question: "What scripture was revealed to Prophet Dawud (David)?",
    options: ["Tawrat", "Zabur (Psalms)", "Injeel", "Suhuf"],
    correctIndex: 1,
    explanation: "Allah granted the Zabur (Psalms) to Prophet Dawud (peace be upon him).",
    source: "Holy Quran, Surah An-Nisa 4:163",
  },
  {
    id: "l3_q8",
    level: 3,
    levelName: "Level 3 — Prophets & Messengers",
    question: "Which Prophet was sent to the people of 'Aad?",
    options: ["Prophet Hud", "Prophet Salih", "Prophet Shu'ayb", "Prophet Lut"],
    correctIndex: 0,
    explanation: "Prophet Hud (peace be upon him) was sent to guide the ancient tribe of 'Aad.",
    source: "Holy Quran, Surah Hud 11:50",
  },
  {
    id: "l3_q9",
    level: 3,
    levelName: "Level 3 — Prophets & Messengers",
    question: "Which miracle was given to Prophet Salih for the people of Thamud?",
    options: ["Staff turning into snake", "The She-Camel", "Splitting of the sea", "Cooling the fire"],
    correctIndex: 1,
    explanation: "Prophet Salih was given the miraculous She-Camel as a clear sign for Thamud.",
    source: "Holy Quran, Surah Al-A'raf 7:73",
  },
  {
    id: "l3_q10",
    level: 3,
    levelName: "Level 3 — Prophets & Messengers",
    question: "How old was Prophet Muhammad ﷺ when he received prophethood?",
    options: ["25", "30", "40", "50"],
    correctIndex: 2,
    explanation: "Prophet Muhammad ﷺ was 40 years old when Jibreel brought the first revelation.",
    source: "Sahih Bukhari, Hadith 3",
  },

  // LEVEL 4
  {
    id: "l4_q1",
    level: 4,
    levelName: "Level 4 — Seerah & History",
    question: "In which year did the major Battle of Badr take place?",
    options: ["1 AH (622 CE)", "2 AH (624 CE)", "3 AH (625 CE)", "5 AH (627 CE)"],
    correctIndex: 1,
    explanation: "The decisive Battle of Badr occurred on the 17th of Ramadan in 2 AH.",
    source: "Ar-Raheeq Al-Makhtum",
  },
  {
    id: "l4_q2",
    level: 4,
    levelName: "Level 4 — Seerah & History",
    question: "Who was the first wife of Prophet Muhammad ﷺ?",
    options: ["Aisha bint Abi Bakr", "Khadijah bint Khuwaylid", "Hafsa bint Umar", "Zaynab bint Jahsh"],
    correctIndex: 1,
    explanation: "Khadijah bint Khuwaylid (may Allah be pleased with her) was the first wife and first believer.",
    source: "Sahih Bukhari, Hadith 3815",
  },
  {
    id: "l4_q3",
    level: 4,
    levelName: "Level 4 — Seerah & History",
    question: "What was the treaty signed between Muslims and Quraysh in 6 AH?",
    options: ["Pact of Madinah", "Treaty of Hudaybiyyah", "Pledge of Ridwan", "Treaty of Taif"],
    correctIndex: 1,
    explanation: "The Treaty of Hudaybiyyah was signed in 6 AH and paved the way for the Conquest of Makkah.",
    source: "Sahih Bukhari, Hadith 2731",
  },
  {
    id: "l4_q4",
    level: 4,
    levelName: "Level 4 — Seerah & History",
    question: "Which companion conquered Jerusalem peacefully during his caliphate?",
    options: ["Abu Bakr as-Siddiq", "Umar ibn al-Khattab", "Uthman ibn Affan", "Ali ibn Abi Talib"],
    correctIndex: 1,
    explanation: "Caliph Umar ibn al-Khattab entered Jerusalem in 637 CE and accepted its peaceful surrender.",
    source: "Tarikh al-Tabari",
  },
  {
    id: "l4_q5",
    level: 4,
    levelName: "Level 4 — Seerah & History",
    question: "Which battle involved digging a defensive trench around Madinah?",
    options: ["Battle of Uhud", "Battle of Khandaq (Trench)", "Battle of Hunayn", "Battle of Khaybar"],
    correctIndex: 1,
    explanation: "The Battle of Khandaq (Ahzab) took place in 5 AH following Salman al-Farsi's strategy.",
    source: "Holy Quran, Surah Al-Ahzab 33",
  },
  {
    id: "l4_q6",
    level: 4,
    levelName: "Level 4 — Seerah & History",
    question: "Who was known as Saifullah (The Sword of Allah)?",
    options: ["Hamza ibn Abdul-Muttalib", "Khalid ibn al-Walid", "Ali ibn Abi Talib", "Sa'd ibn Abi Waqqas"],
    correctIndex: 1,
    explanation: "Khalid ibn al-Walid was bestowed the honorific title Saifullah by Prophet Muhammad ﷺ.",
    source: "Sahih Bukhari, Hadith 3757",
  },
  {
    id: "l4_q7",
    level: 4,
    levelName: "Level 4 — Seerah & History",
    question: "In which year did the Conquest of Makkah (Fath Makkah) occur?",
    options: ["6 AH", "8 AH (630 CE)", "9 AH", "10 AH"],
    correctIndex: 1,
    explanation: "Makkah was liberated peacefully in Ramadan 8 AH.",
    source: "Sahih Bukhari, Hadith 4275",
  },
  {
    id: "l4_q8",
    level: 4,
    levelName: "Level 4 — Seerah & History",
    question: "Which companion migrated to Abyssinia (Habasha) and spoke eloquently before King Negus?",
    options: ["Ja'far ibn Abi Talib", "Bilal ibn Rabah", "Abu Dharr al-Ghifari", "Zayd ibn Harithah"],
    correctIndex: 0,
    explanation: "Ja'far ibn Abi Talib recited Surah Maryam before Negus in Abyssinia.",
    source: "Seerah Ibn Hisham",
  },
  {
    id: "l4_q9",
    level: 4,
    levelName: "Level 4 — Seerah & History",
    question: "Who was the official caller to prayer (Mu'adhdhin) chosen by Prophet Muhammad ﷺ?",
    options: ["Bilal ibn Rabah", "Ibn Umm Maktum", "Abu Hurairah", "Anas ibn Malik"],
    correctIndex: 0,
    explanation: "Bilal ibn Rabah (may Allah be pleased with him) was appointed the chief Mu'adhdhin.",
    source: "Sahih Bukhari, Hadith 603",
  },
  {
    id: "l4_q10",
    level: 4,
    levelName: "Level 4 — Seerah & History",
    question: "Where did Prophet Muhammad ﷺ deliver his famous Farewell Sermon (Khutbat al-Wada')?",
    options: ["Mount Uhud", "Mount Arafat (Jabal al-Rahmah)", "Mina", "Muzdalifah"],
    correctIndex: 1,
    explanation: "The Farewell Sermon was delivered on Mount Arafat during Hajj in 10 AH.",
    source: "Sahih Muslim, Hadith 1218",
  },

  // LEVEL 5
  {
    id: "l5_q1",
    level: 5,
    levelName: "Level 5 — Islamic Jurisprudence & Hadith",
    question: "What is the primary compilation of Hadith compiled by Imam Bukhari called?",
    options: ["Sahih Muslim", "Al-Jami' as-Sahih (Sahih Bukhari)", "Sunan Abu Dawud", "Muwatta Malik"],
    correctIndex: 1,
    explanation: "Sahih Bukhari contains over 7,000 authenticated traditions selected meticulously.",
    source: "Imam al-Bukhari Compilation",
  },
  {
    id: "l5_q2",
    level: 5,
    levelName: "Level 5 — Islamic Jurisprudence & Hadith",
    question: "What are the two most authentic books of Hadith collectively termed?",
    options: ["Al-Kutub al-Sittah", "Sahihayn (The Two Sahihs)", "Sunan Arba'ah", "Masanid"],
    correctIndex: 1,
    explanation: "Sahih Bukhari and Sahih Muslim are collectively called the Sahihayn.",
    source: "Hadith Methodology Literature",
  },
  {
    id: "l5_q3",
    level: 5,
    levelName: "Level 5 — Islamic Jurisprudence & Hadith",
    question: "Which companion narrated the highest number of Hadith statements?",
    options: ["Aisha bint Abi Bakr", "Abu Hurairah", "Abdullah ibn Umar", "Anas ibn Malik"],
    correctIndex: 1,
    explanation: "Abu Hurairah (may Allah be pleased with him) narrated 5,374 Hadiths.",
    source: "Siyar A'lam al-Nubala",
  },
  {
    id: "l5_q4",
    level: 5,
    levelName: "Level 5 — Islamic Jurisprudence & Hadith",
    question: "What is the minimum threshold of wealth for Zakat eligibility called?",
    options: ["Nisab", "Sadaqah", "Ushr", "Kaffarah"],
    correctIndex: 0,
    explanation: "Nisab is the minimum qualifying wealth held for one full lunar year.",
    source: "Sahih Muslim, Hadith 979",
  },
  {
    id: "l5_q5",
    level: 5,
    levelName: "Level 5 — Islamic Jurisprudence & Hadith",
    question: "How many obligatory Sunnah rak'ahs are attached to Fajr prayer?",
    options: ["2", "4", "6", "8"],
    correctIndex: 0,
    explanation: "The two rak'ahs before Fajr are the most emphasized voluntary Sunnah prayer.",
    source: "Sahih Bukhari, Hadith 1163",
  },
  {
    id: "l5_q6",
    level: 5,
    levelName: "Level 5 — Islamic Jurisprudence & Hadith",
    question: "Which night during the last 10 nights of Ramadan is better than a thousand months?",
    options: ["Laylat al-Qadr", "Laylat al-Bara'at", "Night of Isra", "Night of Arafah"],
    correctIndex: 0,
    explanation: "Laylat al-Qadr (Night of Decree) is better in worship than 1,000 months.",
    source: "Holy Quran, Surah Al-Qadr 97:3",
  },
  {
    id: "l5_q7",
    level: 5,
    levelName: "Level 5 — Islamic Jurisprudence & Hadith",
    question: "Which major act of worship requires physical purity (Wudu) and circumambulating Kaaba?",
    options: ["Tawaf", "Sa'i", "Rami al-Jamarat", "I'tikaf"],
    correctIndex: 0,
    explanation: "Tawaf is circumambulation 7 times around the Kaaba.",
    source: "Sahih Bukhari, Hadith 1613",
  },
  {
    id: "l5_q8",
    level: 5,
    levelName: "Level 5 — Islamic Jurisprudence & Hadith",
    question: "What is the dry purification method using clean earth when water is absent called?",
    options: ["Ghusl", "Tayammum", "Istinja", "Masah"],
    correctIndex: 1,
    explanation: "Tayammum is dry ablution performed when clean water is unavailable.",
    source: "Holy Quran, Surah An-Nisa 4:43",
  },
  {
    id: "l5_q9",
    level: 5,
    levelName: "Level 5 — Islamic Jurisprudence & Hadith",
    question: "Which Angel is entrusted with conveying divine revelations to Prophets?",
    options: ["Jibreel (Gabriel)", "Mikail (Michael)", "Israfil", "Izrail"],
    correctIndex: 0,
    explanation: "Angel Jibreel is the archangel of divine revelation.",
    source: "Holy Quran, Surah Al-Baqarah 2:97",
  },
  {
    id: "l5_q10",
    level: 5,
    levelName: "Level 5 — Islamic Jurisprudence & Hadith",
    question: "Which Angel will blow the Trumpet (Sur) signaling the Day of Resurrection?",
    options: ["Jibreel", "Mikail", "Israfil", "Malik"],
    correctIndex: 2,
    explanation: "Angel Israfil is appointed to blow the Trumpet for the Day of Judgment.",
    source: "Sunan al-Tirmidhi, Hadith 2431",
  },
];
