export type QuizQuestion = {
  id: string;
  level: number;
  levelName: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  source: string;
};

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // LEVEL 1
  {
    id: "l1_q1",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "How many Surahs are in the Holy Quran?",
    options: ["100", "114", "120", "110"],
    correctIndex: 1,
    explanation: "The Holy Quran consists of exactly 114 Surahs, starting with Al-Fatihah and ending with An-Nas.",
    source: "Authentic Quranic Compilation",
  },
  {
    id: "l1_q2",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "What is the first revelation sent down to Prophet Muhammad ﷺ?",
    options: ["Surah Al-Fatihah", "Surah Al-Ikhlas", "Surah Al-'Alaq (Iqra)", "Surah Yasin"],
    correctIndex: 2,
    explanation: "The first verses revealed to Prophet Muhammad ﷺ in Cave Hira were the first five verses of Surah Al-'Alaq.",
    source: "Sahih Bukhari, Hadith 3",
  },
  {
    id: "l1_q3",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "How many obligatory daily prayers (Salah) are prescribed for Muslims?",
    options: ["3", "4", "5", "7"],
    correctIndex: 2,
    explanation: "Muslims are obligated to perform 5 daily prayers: Fajr, Dhuhr, Asr, Maghrib, and Isha.",
    source: "Sahih Bukhari, Hadith 8",
  },
  {
    id: "l1_q4",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "In which city was Prophet Muhammad ﷺ born?",
    options: ["Madinah", "Makkah", "Jerusalem", "Taif"],
    correctIndex: 1,
    explanation: "Prophet Muhammad ﷺ was born in the blessed city of Makkah in the Year of the Elephant (570 CE).",
    source: "Ar-Raheeq Al-Makhtum (The Sealed Nectar)",
  },
  {
    id: "l1_q5",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "Which Pillar of Islam comes immediately after the Shahada?",
    options: ["Fasting (Sawm)", "Prayer (Salah)", "Zakat", "Hajj"],
    correctIndex: 1,
    explanation: "Performing the 5 daily prayers (Salah) is the second pillar of Islam.",
    source: "Sahih Bukhari, Hadith 8",
  },
  {
    id: "l1_q6",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "What is the holy book revealed to Prophet Isa (Jesus) peace be upon him?",
    options: ["Tawrat", "Zabur", "Injeel", "Quran"],
    correctIndex: 2,
    explanation: "Allah revealed the Injeel (Gospel) to Prophet Isa (peace be upon him).",
    source: "Holy Quran, Surah Al-Ma'idah 5:46",
  },
  {
    id: "l1_q7",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "Which Islamic month is dedicated to obligatory fasting?",
    options: ["Rajab", "Sha'ban", "Ramadan", "Muharram"],
    correctIndex: 2,
    explanation: "Ramadan is the ninth month of the Islamic calendar in which Muslims observe fasting.",
    source: "Holy Quran, Surah Al-Baqarah 2:185",
  },
  {
    id: "l1_q8",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "What direction do Muslims face during prayer?",
    options: ["Qibla (Kaaba in Makkah)", "North", "East", "Jerusalem"],
    correctIndex: 0,
    explanation: "Muslims face the Qibla, which is the Sacred Kaaba in Makkah, Saudi Arabia.",
    source: "Holy Quran, Surah Al-Baqarah 2:144",
  },
  {
    id: "l1_q9",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "What is the opening Surah of the Quran?",
    options: ["Surah Al-Baqarah", "Surah Al-Fatihah", "Surah Al-Ikhlas", "Surah Al-Nas"],
    correctIndex: 1,
    explanation: "Surah Al-Fatihah ('The Opening') is the first chapter of the Holy Quran.",
    source: "Holy Quran, Surah 1",
  },
  {
    id: "l1_q10",
    level: 1,
    levelName: "Level 1 — Fundamentals",
    question: "Which companion was the first Caliph of Islam?",
    options: ["Umar ibn al-Khattab", "Abu Bakr as-Siddiq", "Uthman ibn Affan", "Ali ibn Abi Talib"],
    correctIndex: 1,
    explanation: "Abu Bakr as-Siddiq (may Allah be pleased with him) was elected as the first Rashidun Caliph.",
    source: "Sahih Bukhari, Hadith 3661",
  },

  // LEVEL 2
  {
    id: "l2_q1",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "What is the longest Surah in the Holy Quran?",
    options: ["Surah Ali 'Imran", "Surah An-Nisa", "Surah Al-Baqarah", "Surah Al-Ma'idah"],
    correctIndex: 2,
    explanation: "Surah Al-Baqarah is the longest Surah containing 286 verses.",
    source: "Holy Quran, Surah 2",
  },
  {
    id: "l2_q2",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which verse in the Quran is considered the greatest verse?",
    options: ["Ayat al-Kursi (2:255)", "Aamanar-Rasul (2:285)", "Surah Al-Ikhlas 1", "Surah Al-Fatihah 1"],
    correctIndex: 0,
    explanation: "Prophet Muhammad ﷺ declared Ayat al-Kursi (Surah Al-Baqarah 2:255) to be the greatest verse in the Quran.",
    source: "Sahih Muslim, Hadith 810",
  },
  {
    id: "l2_q3",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which Surah does not begin with Bismillah?",
    options: ["Surah At-Tawbah", "Surah Al-Anfal", "Surah Yunus", "Surah Hud"],
    correctIndex: 0,
    explanation: "Surah At-Tawbah (Surah 9) is the only chapter in the Quran that does not begin with Bismillah.",
    source: "Holy Quran, Surah At-Tawbah",
  },
  {
    id: "l2_q4",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "In which Surah is Bismillah mentioned twice?",
    options: ["Surah An-Naml", "Surah Al-Kahf", "Surah Ya-Sin", "Surah Ar-Rahman"],
    correctIndex: 0,
    explanation: "Surah An-Naml mentions Bismillah at the beginning and also in verse 30 inside Solomon's letter.",
    source: "Holy Quran, Surah An-Naml 27:30",
  },
  {
    id: "l2_q5",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which Prophet's story is described as 'the best of stories' in the Quran?",
    options: ["Prophet Musa", "Prophet Ibrahim", "Prophet Yusuf", "Prophet Isa"],
    correctIndex: 2,
    explanation: "Surah Yusuf is explicitly described by Allah as 'Ahsan al-Qasas' (the best of stories).",
    source: "Holy Quran, Surah Yusuf 12:3",
  },
  {
    id: "l2_q6",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which Surah is equivalent to one-third of the Quran in reward?",
    options: ["Surah Al-Fatihah", "Surah Al-Ikhlas", "Surah Al-Falaq", "Surah An-Nas"],
    correctIndex: 1,
    explanation: "Reciting Surah Al-Ikhlas is equivalent in reward to reciting one-third of the Quran.",
    source: "Sahih Bukhari, Hadith 5013",
  },
  {
    id: "l2_q7",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "How many Juz are in the Holy Quran?",
    options: ["20", "30", "40", "60"],
    correctIndex: 1,
    explanation: "The Quran is divided into 30 Juz (parts) for recitation structure.",
    source: "Authentic Quranic Structure",
  },
  {
    id: "l2_q8",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which female figure is the only woman mentioned by name in the Quran?",
    options: ["Khadijah", "Aisha", "Maryam (Mary)", "Asiya"],
    correctIndex: 2,
    explanation: "Maryam, the mother of Prophet Isa (peace be upon him), is the only woman explicitly named in the Quran.",
    source: "Holy Quran, Surah Maryam 19",
  },
  {
    id: "l2_q9",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which Surah protects its reciter from the punishment of the grave?",
    options: ["Surah Al-Mulk", "Surah Al-Kahf", "Surah Ya-Sin", "Surah Al-Waqi'ah"],
    correctIndex: 0,
    explanation: "Prophet Muhammad ﷺ said that Surah Al-Mulk (30 verses) intercedes for its reader until forgiven.",
    source: "Sunan an-Nasa'i, Hadith 10479",
  },
  {
    id: "l2_q10",
    level: 2,
    levelName: "Level 2 — Quranic Knowledge",
    question: "Which Surah recommended to be read every Friday protects from Dajjal?",
    options: ["Surah Al-Kahf", "Surah Al-Baqarah", "Surah Yasin", "Surah Ar-Rahman"],
    correctIndex: 0,
    explanation: "Memorizing the first ten verses of Surah Al-Kahf protects against the trial of Dajjal.",
    source: "Sahih Muslim, Hadith 809",
  },
];
